// All 16 Chance + 16 Community Chest card definitions

export type CardActionType =
  | 'bank_give'    // bank pays player a fixed amount
  | 'player_pay'   // player pays bank a fixed amount
  | 'salary'       // advance to GO — collect $200 from bank
  | 'repairs'      // pay per house / hotel owned
  | 'birthday'     // collect fixed amount from every other player
  | 'display';     // movement / jail / GOOJF — no automatic money

export interface MonopolyCard {
  id: string;
  deck: 'chance' | 'community';
  emoji: string;
  title: string;
  description: string;
  action: CardActionType;
  amount?: number;        // for bank_give / player_pay / birthday / salary
  houseAmount?: number;   // for repairs
  hotelAmount?: number;   // for repairs
  hasGoBonus?: boolean;   // movement cards where passing GO is possible
}

export const CHANCE_CARDS: MonopolyCard[] = [
  {
    id: 'ch_go',
    deck: 'chance',
    emoji: '🏁',
    title: 'Advance to GO',
    description: 'Move directly to GO and collect $200 from the bank.',
    action: 'salary',
    amount: 200,
  },
  {
    id: 'ch_illinois',
    deck: 'chance',
    emoji: '🚗',
    title: 'Advance to Illinois Avenue',
    description: 'Move your token to Illinois Ave. If you pass GO, collect $200.',
    action: 'display',
    hasGoBonus: true,
  },
  {
    id: 'ch_stcharles',
    deck: 'chance',
    emoji: '🚗',
    title: 'Advance to St. Charles Place',
    description: 'Move your token to St. Charles Place. If you pass GO, collect $200.',
    action: 'display',
    hasGoBonus: true,
  },
  {
    id: 'ch_utility',
    deck: 'chance',
    emoji: '⚡',
    title: 'Advance to Nearest Utility',
    description: 'Move to the Electric Company or Water Works. If owned, throw the dice and pay the owner 10× the amount thrown. If unowned, you may buy it.',
    action: 'display',
  },
  {
    id: 'ch_railroad1',
    deck: 'chance',
    emoji: '🚂',
    title: 'Advance to Nearest Railroad',
    description: 'Move to the nearest Railroad. If owned, pay the owner twice the usual rent. If unowned, you may buy it.',
    action: 'display',
  },
  {
    id: 'ch_railroad2',
    deck: 'chance',
    emoji: '🚂',
    title: 'Advance to Nearest Railroad',
    description: 'Move to the nearest Railroad. If owned, pay the owner twice the usual rent. If unowned, you may buy it.',
    action: 'display',
  },
  {
    id: 'ch_reading',
    deck: 'chance',
    emoji: '🚂',
    title: 'Advance to Reading Railroad',
    description: 'Move your token directly to Reading Railroad. If you pass GO, collect $200.',
    action: 'display',
    hasGoBonus: true,
  },
  {
    id: 'ch_boardwalk',
    deck: 'chance',
    emoji: '🏖️',
    title: 'Advance to Boardwalk',
    description: 'Move your token directly to Boardwalk.',
    action: 'display',
  },
  {
    id: 'ch_dividend',
    deck: 'chance',
    emoji: '💰',
    title: 'Bank Pays You Dividend',
    description: 'The bank pays you a dividend of $50.',
    action: 'bank_give',
    amount: 50,
  },
  {
    id: 'ch_goojf',
    deck: 'chance',
    emoji: '🆓',
    title: 'Get Out of Jail Free',
    description: 'Keep this card until you need it, then discard it. You may sell this card to another player.',
    action: 'display',
  },
  {
    id: 'ch_goback3',
    deck: 'chance',
    emoji: '⬅️',
    title: 'Go Back 3 Spaces',
    description: 'Move your token backward 3 spaces on the board.',
    action: 'display',
  },
  {
    id: 'ch_jail',
    deck: 'chance',
    emoji: '🔒',
    title: 'Go to Jail',
    description: 'Go directly to Jail. Do not pass GO. Do not collect $200.',
    action: 'display',
  },
  {
    id: 'ch_repairs',
    deck: 'chance',
    emoji: '🏠',
    title: 'Make General Repairs',
    description: 'Make general repairs on all your property. Pay $25 per house and $100 per hotel you own.',
    action: 'repairs',
    houseAmount: 25,
    hotelAmount: 100,
  },
  {
    id: 'ch_fine',
    deck: 'chance',
    emoji: '💸',
    title: 'Speeding Fine',
    description: 'Pay a speeding fine of $15 to the bank.',
    action: 'player_pay',
    amount: 15,
  },
  {
    id: 'ch_reading2',
    deck: 'chance',
    emoji: '🚂',
    title: 'Take a Trip to Reading Railroad',
    description: 'Move your token to Reading Railroad. If you pass GO, collect $200.',
    action: 'display',
    hasGoBonus: true,
  },
  {
    id: 'ch_loan',
    deck: 'chance',
    emoji: '🏦',
    title: 'Your Building Loan Matures',
    description: 'Your building loan matures — receive $150 from the bank.',
    action: 'bank_give',
    amount: 150,
  },
];

export const COMMUNITY_CHEST_CARDS: MonopolyCard[] = [
  {
    id: 'cc_go',
    deck: 'community',
    emoji: '🏁',
    title: 'Advance to GO',
    description: 'Move directly to GO and collect $200 from the bank.',
    action: 'salary',
    amount: 200,
  },
  {
    id: 'cc_bank_error',
    deck: 'community',
    emoji: '🏦',
    title: 'Bank Error in Your Favor',
    description: 'Bank error in your favor — collect $200 from the bank.',
    action: 'bank_give',
    amount: 200,
  },
  {
    id: 'cc_doctor',
    deck: 'community',
    emoji: '🩺',
    title: "Doctor's Fees",
    description: "Pay doctor's fees of $50 to the bank.",
    action: 'player_pay',
    amount: 50,
  },
  {
    id: 'cc_stock',
    deck: 'community',
    emoji: '📈',
    title: 'From Sale of Stock',
    description: 'From sale of stock — receive $50 from the bank.',
    action: 'bank_give',
    amount: 50,
  },
  {
    id: 'cc_goojf',
    deck: 'community',
    emoji: '🆓',
    title: 'Get Out of Jail Free',
    description: 'Keep this card until you need it, then discard it. You may sell this card to another player.',
    action: 'display',
  },
  {
    id: 'cc_jail',
    deck: 'community',
    emoji: '🔒',
    title: 'Go to Jail',
    description: 'Go directly to Jail. Do not pass GO. Do not collect $200.',
    action: 'display',
  },
  {
    id: 'cc_holiday',
    deck: 'community',
    emoji: '🏖️',
    title: 'Holiday Fund Matures',
    description: 'Your holiday fund matures — collect $100 from the bank.',
    action: 'bank_give',
    amount: 100,
  },
  {
    id: 'cc_taxrefund',
    deck: 'community',
    emoji: '💵',
    title: 'Income Tax Refund',
    description: 'Income tax refund — collect $200 from the bank.',
    action: 'bank_give',
    amount: 200,
  },
  {
    id: 'cc_birthday',
    deck: 'community',
    emoji: '🎂',
    title: 'It Is Your Birthday',
    description: 'It is your birthday! Collect $10 from every other player.',
    action: 'birthday',
    amount: 10,
  },
  {
    id: 'cc_insurance',
    deck: 'community',
    emoji: '📋',
    title: 'Life Insurance Matures',
    description: 'Your life insurance matures — collect $100 from the bank.',
    action: 'bank_give',
    amount: 100,
  },
  {
    id: 'cc_hospital',
    deck: 'community',
    emoji: '🏥',
    title: 'Pay Hospital Fees',
    description: 'Pay hospital fees of $100 to the bank.',
    action: 'player_pay',
    amount: 100,
  },
  {
    id: 'cc_school',
    deck: 'community',
    emoji: '🏫',
    title: 'Pay School Fees',
    description: 'Pay school fees of $50 to the bank.',
    action: 'player_pay',
    amount: 50,
  },
  {
    id: 'cc_consultancy',
    deck: 'community',
    emoji: '💼',
    title: 'Receive Consultancy Fee',
    description: 'Receive $25 consultancy fee from the bank.',
    action: 'bank_give',
    amount: 25,
  },
  {
    id: 'cc_street_repairs',
    deck: 'community',
    emoji: '🏗️',
    title: 'Street Repairs Assessment',
    description: 'You are assessed for street repairs: pay $40 per house and $115 per hotel you own.',
    action: 'repairs',
    houseAmount: 40,
    hotelAmount: 115,
  },
  {
    id: 'cc_beauty',
    deck: 'community',
    emoji: '🏆',
    title: 'Second Prize — Beauty Contest',
    description: 'You have won second prize in a beauty contest — collect $10 from the bank.',
    action: 'bank_give',
    amount: 10,
  },
  {
    id: 'cc_inherit',
    deck: 'community',
    emoji: '💌',
    title: 'You Inherit $100',
    description: 'You inherit $100 — collect from the bank.',
    action: 'bank_give',
    amount: 100,
  },
];
